// Copyright (c) Microsoft Corporation. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.


namespace Microsoft.IIS.Administration.WebServer
{
    using Core;
    using System;
    using System.IO;

    /// <summary>
    /// Serializes applicationHost.config commits across requests. IIS stores configuration in a single
    /// file, so concurrent commits race: the loser observes "the file has changed on disk" and
    /// Microsoft.Web.Administration surfaces it as a FileLoadException
    /// (https://github.com/microsoft/IIS.Administration/issues/324). The static lock is an in-process
    /// guard, so it only serializes commits originating from this process. Residual cross-process races
    /// (IIS Manager, appcmd, or another instance writing the file) cannot be locked out here; they still
    /// surface as the same FileLoadException, which the gate converts into HTTP 409 so clients can retry.
    /// </summary>
    static class ConfigCommitGate
    {
        private static readonly object _lock = new object();

        public static void Commit(Action commitChanges)
        {
            if (commitChanges == null) {
                throw new ArgumentNullException(nameof(commitChanges));
            }

            lock (_lock) {
                try {
                    commitChanges();
                }
                catch (FileLoadException e) {
                    //
                    // Microsoft.Web.Administration surfaces the applicationHost.config read-modify-write
                    // race as a FileLoadException whose message ("...the file has changed on disk") is
                    // generated by native IIS config and is LOCALIZED on non-English hosts. The native
                    // failure is ERROR_FILE_CHANGED (HRESULT 0x800703EE), so match on that HResult as a
                    // language-independent signal in addition to the English message. FileLoadException is
                    // also raised for unrelated assembly-load failures (COR_E_FILELOAD, 0x80131621), which
                    // must keep propagating untouched.
                    const int ERROR_FILE_CHANGED = unchecked((int)0x800703EE);

                    bool isConfigChangedOnDisk =
                        e.HResult == ERROR_FILE_CHANGED ||
                        e.Message.IndexOf("changed on disk", StringComparison.OrdinalIgnoreCase) >= 0;

                    if (!isConfigChangedOnDisk) {
                        //
                        // Either a genuine assembly-load failure (propagate as an honest 500) or a localized
                        // commit-race we failed to recognize. Trace it with the exact HResult/message so a
                        // localized miss is diagnosable instead of a silent 500, then re-throw unchanged.
                        System.Diagnostics.Trace.TraceWarning(
                            $"ConfigCommitGate: unmatched FileLoadException (HResult=0x{e.HResult:X8}): {e.Message}");
                        throw;
                    }

                    throw new ConfigurationConflictException(
                        "IIS configuration was modified by another change. Retry the request.", e);
                }
            }
        }
    }
}
